module.exports = {
	url: 'https://api.apify.com/v2/key-value-stores/tVaYRsPHLjNdNBu7S/records/LATEST?disableRedirect=true',
	allowed_countries: [
		'United States',
		'India',
		'Brazil',
		'France',
		'Turkey',
		'Russia',
		'United Kingdom',
		'Italy',
		'German',
		'Spain',
		'Iran',
		'Poland',
		'Netherlands',
		'Czech Republic',
		'Canada',
		'Chile',
		'Philippines',
		'Romania',
		'Sweden',
		'Belgium',
		'Pakistan',
		'Portugal',
		'Hungary',
		'Japan',
		'Serbia',
		'Switzerland',
		'Malaysia',
		'Saudi Arabia',
		'Bulgaria',
		'Slovakia',
		'Palestine',
		'Azerbaijan',
		'Slovenia',
		'Bahrain',
		'Honduras',
		'Denmark',
		'Nigeria',
		'South Korea',
		'Algeria',
		'Norway',
		'Estonia',
		'Finland',
		'China',
		'Luxembourg',
		'Singapore',
		'Vietnam',
		'Lithuania',
		'Croatia',
		'Austria',
	]
}